services:

  database:
    profiles: [ all, backend, database ]
    build: database
    image: {{ cookiecutter.project_slug }}/database:latest
    container_name: {{ cookiecutter.project_slug }}-database
    ports:
      - "{{ cookiecutter.database_port }}:{{ cookiecutter.database_port }}"
    volumes:
      - {{ cookiecutter.project_slug }}_database:/var/lib/postgresql/data
    env_file:
      - database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

volumes:
  {{ cookiecutter.project_slug }}_database:
